# Stage 1: Build TypeScript to JS
FROM node:22-alpine AS builder

WORKDIR /app

# Copy only essential files for install & build
COPY package*.json tsconfig.json ./

# Install dependencies
RUN npm install

# Copy TypeScript source files
COPY ./src ./src

# Build TypeScript to JavaScript
RUN npm run build

# Stage 2: Run compiled JS
FROM node:22-alpine

WORKDIR /app

# Copy only required files for production
COPY package*.json ./
RUN npm install --only=production

# Copy the compiled JS files from the builder stage
COPY --from=builder /app/dist ./dist

# Expose the port
EXPOSE 8000

# Run the app
CMD ["node", "dist/index.js"]
