import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

// Styles
const styles = StyleSheet.create({
  page: {
    paddingTop: 60,
    paddingBottom: 60,
    paddingHorizontal: 40,
    fontFamily: 'Helvetica',
    fontSize: 12,
    backgroundColor: '#ffffff',
    color: '#111827',
  },
  header: {
    position: 'absolute',
    top: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1e3a8a',
    textTransform: 'uppercase',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingBottom: 5,
  },
  subHeader: {
    fontSize: 10,
    color: '#374151',
    marginTop: 4,
    textAlign: 'center',
  },
  title: {
    fontSize: 22,
    marginBottom: 25,
    marginTop: 40,
    textAlign: 'center',
    color: '#1e40af',
    fontWeight: 'bold',
    textDecoration: 'underline',
  },
  section: {
    marginVertical: 10,
    paddingHorizontal: 10,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  label: {
    width: 150,
    fontWeight: 700,
    color: '#1f2937',
  },
  value: {
    flex: 1,
    color: '#374151',
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: '#d1d5db',
    marginVertical: 15,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 10,
    color: '#6b7280',
    textAlign: 'center',
    borderTopWidth: 1,
    borderTopColor: '#d1d5db',
    paddingTop: 5,
  },
});

// PDF Component
const ReportTemplate = ({ data }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      
      {/* Official Header */}
      <Text style={styles.header}>Sri Lanka Police Department</Text>
      <Text style={styles.subHeader}>Lost & Found Reporting System</Text>

      {/* Title */}
      <Text style={styles.title}>{data.type === 'lost' ? 'Lost Item Report' : 'Found Item Report'}</Text>

      {/* Report Content */}
      <View style={styles.section}>

        <View style={styles.row}>
          <Text style={styles.label}>Reference No:</Text>
          <Text style={styles.value}>{data.referanceNo}</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Item:</Text>
          <Text style={styles.value}>{data.item}</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Category:</Text>
          <Text style={styles.value}>{data.category?.join(', ')}</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Reported By:</Text>
          <Text style={styles.value}>{data.name}</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Phone No:</Text>
          <Text style={styles.value}>{data.phoneNo}</Text>
        </View>

        <View style={styles.divider} />

        <View style={styles.row}>
          <Text style={styles.label}>{data.type === 'lost' ? 'Lost Date:' : 'Found Date:'}</Text>
          <Text style={styles.value}>{data.date}</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>District:</Text>
          <Text style={styles.value}>{data.district}</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Location:</Text>
          <Text style={styles.value}>{data.location}</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Police Station:</Text>
          <Text style={styles.value}>{data.station}</Text>
        </View>

        <View style={styles.divider} />

        <View style={styles.row}>
          <Text style={styles.label}>Status:</Text>
          <Text style={styles.value}>{data.status}</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Created At:</Text>
          <Text style={styles.value}>{new Date(data.createdAt).toLocaleString()}</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Last Updated:</Text>
          <Text style={styles.value}>{new Date(data.updatedAt).toLocaleString()}</Text>
        </View>
      </View>

      {/* Footer */}
      <Text style={styles.footer}>
        Generated by LFRS • Sri Lanka Police | Date: {new Date().toLocaleDateString()}
      </Text>
    </Page>
  </Document>
);

export default ReportTemplate;
